title: EcoVecinos
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Ecovecinos. Proyecto Respeto.
baseurl: /ecovecinos # the subpath of your site, e.g. /blog
url: https://respeto.org.ar # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

host: 0.0.0.0
